---
# tasks file for windows-docker-role

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Update Powershell
  ansible.windows.win_package:
    path: "{{ powershell.msi_address }}"
    product_id: "{{ powershell.product_id }}"
  register: powershell_res

- name: Reboot if required
  win_reboot:
    reboot_timeout: "{{ powershell.install_reboot_timeout }}"
  when: powershell_res.reboot_required

- name: Check nuget is installed
  win_shell: Get-PackageProvider Nuget -ListAvailable
  register: nuget_check
  changed_when: false
  ignore_errors: true
  
- name: Ensure Nuget is installed
  win_shell: |
    $result = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
    $exitCode = $?
    if($exitCode -eq "0") {
      $installedVersion = [System.Version]($result)[0].Version
      $minSupportedVersion = [System.Version]"{{expected_nuget_minimum_version}}"
      echo "$installedVersion > $minSupportedVersion"
      if($installedVersion -gt $minSupportedVersion) {
        exit 0
      } else {
        exit 1
      }
    } else {
      exit $exitCode
    }
  register: nuget_res
  when: nuget_check.stderr != ""


- name: Ensure PowerShellGet is installed
  win_psmodule:
    name: "PowerShellGet"
    minimum_version: "{{ powershellget.minimum_version }}"

- name: Ensure DockerMsftProvider is installed
  win_psmodule:
    name: "DockerMsftProvider"
    repository: "PSGallery"

- name: Install latest Docker version
  win_dsc:
    resource_name: PackageManagement
    Name: "docker"
    ProviderName: DockerMsftProvider
  notify:
    - Restart server following Docker changes
  when: docker.version == "latest"

- name: Install specific Docker version
  win_dsc:
    resource_name: PackageManagement
    Name: "docker"
    ProviderName: DockerMsftProvider
    RequiredVersion: "{{ docker.version }}"
  notify:
    - Restart server following Docker changes
  when: docker.version != "latest"

- name: Make certificate directories
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - C:\Docker-SSL\client\.docker
    - C:\Docker-SSL\server

- name: Open necessary ports
  win_shell: |
    Import-Module NetSecurity
    $prot = "{{ item.protocol }}"
    $port = "{{ item.port }}"
    [Microsoft.PowerShell.Cmdletization.GeneratedTypes.NetSecurity.Profile] $profile = "{{ item.profile }}"
    [Microsoft.PowerShell.Cmdletization.GeneratedTypes.NetSecurity.Direction] $direction = "{{ item.direction }}"
    $name = "{{ item.name }}"

    [Microsoft.PowerShell.Cmdletization.GeneratedTypes.NetSecurity.Direction] $inbound = "Inbound"
    [bool] $found = $false


    $portfilters = (Get-NetFirewallPortFilter | Where-Object {$_.LocalPort -eq $port})
    foreach($portfilter in $portfilters)
    {
        $rule = ($portfilter | Get-NetFirewallRule)
        if(
            $rule.DisplayName -eq $name -And
            $rule.Enabled -eq $true -And
            $rule.Action -eq "Allow" -And
            $rule.Direction.CompareTo($direction) -eq 0 -And
            $rule.Profile.CompareTo($profile) -eq 0
        )
        {
            $found = $true
        }
    }

    if(!$found)
    {
        echo "${direction} ${port}/${prot} ${profile}: Not found, adding!"
        New-NetFirewallRule -DisplayName $name -LocalPort $port -Profile $profile -Direction $direction -Protocol $prot
        $res = $?
        if($res -eq $true)
        {
          exit 0
        }
        else
        {
          exit 2
        }
    }
    else
    {
        echo "${direction} ${port}/${prot} ${profile}: Found!"
        exit 1
    }
  loop:
    - { port: 2376, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Inbound", name: "Docker TLS port"}
    - { port: 2377, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Inbound", name: "Docker cluster management communications"}
    - { port: 7946, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Inbound", name: "Docker node communications (TCP)" }
    - { port: 7946, protocol: "UDP", profile: "{{ docker.firewallprofile }}", direction: "Inbound", name: "Docker node communications (UDP)" }
    - { port: 4789, protocol: "UDP", profile: "{{ docker.firewallprofile }}", direction: "Inbound", name: "Docker overlay network traffic" }
    - { port: 2376, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Outbound", name: "Docker TLS port"}
    - { port: 2377, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Outbound", name: "Docker cluster management communications"}
    - { port: 7946, protocol: "TCP", profile: "{{ docker.firewallprofile }}", direction: "Outbound", name: "Docker node communications (TCP)" }
    - { port: 7946, protocol: "UDP", profile: "{{ docker.firewallprofile }}", direction: "Outbound", name: "Docker node communications (UDP)" }
    - { port: 4789, protocol: "UDP", profile: "{{ docker.firewallprofile }}", direction: "Outbound", name: "Docker overlay network traffic" }
  changed_when: firewall_res.rc == 0
  failed_when: firewall_res.rc == 2
  register: firewall_res
  when: setup_firewall_rules | bool

- name: Flush handlers to reboot if necessary.
  meta: flush_handlers

- name: Make sure docker is started
  win_service:
    name: Docker
    state: started
