# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "win2019core" do |core|
    core.vm.box = "jimbo8098/windows2019core"
    core.vm.communicator = "winrm"
    core.winrm.ssl_peer_verification = false
    core.winrm.transport = :ssl
    core.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.groups = {
      "all:vars" => {
        "ansible_winrm_server_cert_validation" => "ignore"
      }
    }
    ansible.verbose = "v"
  end
end
